Repository ShymPyo/shympyo-backend, pull requests merged in 2025-10, with the labels that each got.

#46 [Feat] 날씨, 온도 표출 기능 추가
  src/main/java/shympyo/auth/config/SecurityConfig.java
  src/main/java/shympyo/weather/controller/WeatherController.java
  src/main/java/shympyo/weather/dto/WeatherResponse.java
  src/main/java/shympyo/weather/service/WeatherService.java
Labels: 규원, 진행중

#49 [Feat] 신고/차단 서비스 구현
  src/main/java/shympyo/global/config/JpaConfig.java
  src/main/java/shympyo/global/util/weather/controller/WeatherController.java
  src/main/java/shympyo/global/util/weather/dto/WeatherResponse.java
  src/main/java/shympyo/global/util/weather/service/WeatherService.java
  src/main/java/shympyo/map/controller/MapController.java
  src/main/java/shympyo/map/service/MapService.java
  src/main/java/shympyo/rental/controller/PlaceController.java
  src/main/java/shympyo/rental/repository/PlaceRepository.java
  src/main/java/shympyo/rental/repository/RentalRepository.java
  src/main/java/shympyo/rental/service/PlaceService.java
  src/main/java/shympyo/report/controller/BlockController.java
  src/main/java/shympyo/report/controller/ReportController.java
  src/main/java/shympyo/report/domain/Report.java
  src/main/java/shympyo/report/domain/ReportAction.java
  src/main/java/shympyo/report/domain/ReportReason.java
  src/main/java/shympyo/report/domain/ReportStatus.java
  src/main/java/shympyo/report/domain/ReportTargetType.java
  src/main/java/shympyo/report/domain/Sanction.java
  src/main/java/shympyo/report/domain/SanctionReason.java
  src/main/java/shympyo/report/domain/SanctionScope.java
  src/main/java/shympyo/report/domain/SanctionSource.java
  src/main/java/shympyo/report/domain/SanctionStatus.java
  src/main/java/shympyo/report/domain/SanctionType.java
  src/main/java/shympyo/report/dto/ProviderBlockUserDetailResponse.java
  src/main/java/shympyo/report/dto/ProviderBlockUserRequest.java
  src/main/java/shympyo/report/dto/ProviderBlockUserResponse.java
  src/main/java/shympyo/report/dto/ProviderCreateReportRequest.java
  src/main/java/shympyo/report/repository/ReportRepository.java
  src/main/java/shympyo/report/repository/SanctionRepository.java
  src/main/java/shympyo/report/service/BlockService.java
  src/main/java/shympyo/report/service/ReportService.java
  src/main/java/shympyo/report/service/SanctionService.java
Labels: 민혁, 완료

#50 [Release] v1.0.5 신고/차단 서비스 추가
  src/main/java/shympyo/auth/config/SecurityConfig.java
  src/main/java/shympyo/global/config/JpaConfig.java
  src/main/java/shympyo/global/util/weather/controller/WeatherController.java
  src/main/java/shympyo/global/util/weather/dto/WeatherResponse.java
  src/main/java/shympyo/global/util/weather/service/WeatherService.java
  src/main/java/shympyo/map/controller/MapController.java
  src/main/java/shympyo/map/service/MapService.java
  src/main/java/shympyo/rental/controller/PlaceController.java
  src/main/java/shympyo/rental/repository/PlaceRepository.java
  src/main/java/shympyo/rental/repository/RentalRepository.java
  src/main/java/shympyo/rental/service/PlaceService.java
  src/main/java/shympyo/report/controller/BlockController.java
  src/main/java/shympyo/report/controller/ReportController.java
  src/main/java/shympyo/report/domain/Report.java
  src/main/java/shympyo/report/domain/ReportAction.java
  src/main/java/shympyo/report/domain/ReportReason.java
  src/main/java/shympyo/report/domain/ReportStatus.java
  src/main/java/shympyo/report/domain/ReportTargetType.java
  src/main/java/shympyo/report/domain/Sanction.java
  src/main/java/shympyo/report/domain/SanctionReason.java
  src/main/java/shympyo/report/domain/SanctionScope.java
  src/main/java/shympyo/report/domain/SanctionSource.java
  src/main/java/shympyo/report/domain/SanctionStatus.java
  src/main/java/shympyo/report/domain/SanctionType.java
  src/main/java/shympyo/report/dto/ProviderBlockUserDetailResponse.java
  src/main/java/shympyo/report/dto/ProviderBlockUserRequest.java
  src/main/java/shympyo/report/dto/ProviderBlockUserResponse.java
  src/main/java/shympyo/report/dto/ProviderCreateReportRequest.java
  src/main/java/shympyo/report/repository/ReportRepository.java
  src/main/java/shympyo/report/repository/SanctionRepository.java
  src/main/java/shympyo/report/service/BlockService.java
  src/main/java/shympyo/report/service/ReportService.java
  src/main/java/shympyo/report/service/SanctionService.java
Labels: 서버 배포

#54 [Fix] 차단/신고 엔드포인트 수정
  src/main/java/shympyo/report/controller/BlockController.java
Labels: 서버 배포
